# Generated by Django 3.1.1 on 2022-01-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='room'),
        ),
    ]
