# Generated by Django 3.1.1 on 2022-01-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0004_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_motto', models.CharField(max_length=255)),
                ('about_us', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'company_name',
            },
        ),
    ]
