# Generated by Django 3.1.1 on 2022-01-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0006_auto_20220105_0252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'AboutUs'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
