# Generated by Django 3.1.1 on 2022-01-05 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0007_auto_20220105_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('profile', models.FileField(blank=True, null=True, upload_to='comment_profile')),
                ('commenter', models.CharField(max_length=40)),
                ('main_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.blog')),
            ],
            options={
                'verbose_name_plural': 'BlogComment',
            },
        ),
    ]
