# Generated by Django 3.1.1 on 2022-01-05 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0008_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='comment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
