# Generated by Django 3.1.1 on 2022-01-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0009_blogcomment_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='about_page_image',
            field=models.FileField(blank=True, null=True, upload_to='company_image'),
        ),
    ]
