# Generated by Django 3.1.1 on 2022-01-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0010_aboutus_about_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_quality',
            field=models.CharField(choices=[('presidential', 'presidential'), ('luxury', 'luxury'), ('deluxe', 'deluxe')], default='deluxe', max_length=50),
        ),
    ]
