# Generated by Django 3.1.1 on 2022-01-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0011_room_room_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='phone',
            field=models.CharField(default=4, max_length=20),
            preserve_default=False,
        ),
    ]
