# Generated by Django 3.1.1 on 2022-01-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0013_auto_20220106_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Contact Page'},
        ),
        migrations.AlterField(
            model_name='room',
            name='details',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
